### ISSUE TITLE
Hud crashing at Pokerstars tournement

### ISSUE THREAD

**Issue by wangee** [jejellyroll-fr/fpdb-3#1]
Hello,

First of all great job you've done to port fpdb to python3.

Next, I tested on PS.    Cash games seems to be working (but require more investigations)
For tournaments, the hands are imported but the hud crashes at first hand.

`hid 118
self.caller.pipe_to_hud <Popen: returncode: None args: ['/home/xxx/fpdb-3-main/pyfpdb/HUD_mai...>
self.caller.pipe_to_hud.stdin.write <built-in method write of _io.TextIOWrapper object at 0x7ff16c3c9e50>
fpdb_import: sending hand to hud 118 pipe = <Popen: returncode: None args: ['/home/xxx/fpdb-3-main/pyfpdb/HUD_mai...>
DEBUG: _import_summary_file.ttime: 0.008 hh
Received hand no 118
new_hand_id in read_stdin 118
HUD_main.read_stdin: Hand processing starting.
self.caller2: <GuiAutoImport.GuiAutoImport object at 0x7ff16c450790>
Traceback (most recent call last):
  File "/home/xxx/fpdb-3-main/pyfpdb/HUD_main.pyw", line 386, in read_stdin
    tablewindow = Tables.Table(self.config, site_name, **table_kwargs)
  File "/home/xxx/fpdb-3-main/pyfpdb/TableWindow.py", line 101, in __init__
    self.table = int(table_number)
ValueError: invalid literal for int() with base 10: '3439459704 1'`

It looks like the table number is not properly detected.   Probably that PS changed the way they display windows titles for tournaments.

at TableWindow.py line 101, I splitted table_name and kept the first element as the table_name.   
The HUD stopped crashing, but I'm not good enough at python and could not find how fpdb grabs the table name from Pokerstars.

I've also seen that lots of poker rooms such as Full Tilt, Everest, Absolute etc can be used with fpdb, but they're all dead so in my opinion there are no more reason to keep them, a little cleanup could be a good thing, what are your thoughts about it ?

**Comment by jejellyroll-fr** [comment]
Hello wangee

Thank you for your feedback, it's very motivating.
I'm going to be on vacation, so I'll have a little more time to look at all this and try to correct.
Indeed I am open to all proposals, we could clean all the rooms that no longer exist.

**Comment by jejellyroll-fr** [comment]
Hello wangee

can you tell me what exact change you made in the code?

**Comment by jejellyroll-fr** [comment]
Hello wangee

can you tell me  which Os you are using (win 11,10 7?)

**Comment by jejellyroll-fr** [comment]
Hello Wangee

temp bug correction for stars tour must investigate (and test other rooms)

**Comment by jejellyroll-fr** [comment]
Hello Wangee

the bug seems to me fixed ... I will close this ticket
