### ISSUE TITLE
[FEATURE] move dead code to a particular subdir

### ISSUE THREAD

**Issue by brunetton** [jejellyroll-fr/fpdb-3#19]
As a future contributor to the project I think it would be clearer to clean the repo; ie move "dead code" and tests files to sub-dirs clearly identified ("WIP" or something like this).

Example: OddsCalcnew.py and OddsCalcNew2.py are not used by the program and should be moved to this subdir. Notebooks could be moved to this subdir too.

What do you think about ?

**Comment by jejellyroll-fr** [comment]
I agree ... i started to iterate locally on new structure for this project, some structural modifications are more complex than I thought but we can start with easiest things:

fpdb/
├── core/

├── parsers/

├── utils/

├── gui/

├── webui+apis/

├── tests/
     -> all tests
├── docs/
      -> notebooks and puml(i would like to move to mermaid)
├── archives/
      -> old scripts
      
but i'am open to any suggestions ;)

**Comment by brunetton** [comment]
Looks good to me :)
