### ISSUE TITLE
[ISSUE] AttributeError: 'QComboBox' object has no attribute 'text' when editing HUD

### ISSUE THREAD

**Issue by brunetton** [jejellyroll-fr/fpdb-3#33]
**Describe the bug**
UI crashes when trying to edit HUDs configuration

```
Traceback (most recent call last):
  File "/home/bruno/dev/forks/fpdb-3/./fpdb.pyw", line 235, in dia_hud_preferences
    self.config.edit_hud(result, self.stat2_dict[y].text(), self.stat3_dict[y].text(),
AttributeError: 'QComboBox' object has no attribute 'text'
```

**To Reproduce**
1. configure -> HUD settings
2. select a HUD to edit
3. click on Save

 - Version: dev

=> I've solved it, I'll quickly submit a PR with the fix

**Comment by jejellyroll-fr** [comment]
tx Bruno for you PR and improvement ;)
