### ISSUE TITLE
[ISSUE] HUD - ERROR - TableWindow - __init__ - Can't find table "812751290 0012" with search string "Winamax\s+([^\(]+)\(812751290\)\(#012\)"

### ISSUE THREAD

**Issue by brunetton** [jejellyroll-fr/fpdb-3#56]
**Describe the bug**
FPDB can't find table for [Winamax Poker Tour](https://www.winamax.fr/winamax-poker-tour) tournament 

**To Reproduce**
1. Play a winamax poker tour tournament
2. Start HUD
3. HH file is found and parsed correctly: we see in HUD logs messages like

       20241024_Tremplin Paris(812751290)_real_holdem_no-limit.txt 1 stored, 0 duplicates, 0 partial, 0 skipped, 0 errors (time = 0.077475).....................

5. But no HUD is displayed
6. Logs helps understand that window is not found:

       hud - ERROR - TableWindow - __init__ - Can't find table "812751290 0012" with search string "Winamax\s+([^\(]+)\(812751290\)\(#012\)"

The actual table name (using `xprop`) is `Winamax Tremplin Paris(812751290)(#0012)`

**Expected behavior**
HUD should be attached to the table's window

**Desktop (please complete the following information):**
 - Version: current dev a9c64f1484524755cf455df82d1b032b7b0273

**Proposal**
I'll look deeper as I need a HUD for this tournament; and more generally it would be great to let user specify on which table HUD should be attached.

**Comment by brunetton** [comment]
Quickfix: 

```diff
--- WinamaxToFpdb.py
+++ WinamaxToFpdb.py
@@ -618,12 +618,7 @@ class Winamax(HandHistoryConverter):
             regex = f"Winamax {table_name} /"
         log.debug("regex get table cash title:", regex)
         if tournament:
-            if table_number > 99 or (table_number >= 100 or table_number <= 9) and table_number == 0:
-                regex = r"Winamax\s+([^\(]+)\(%s\)\(#%s\)" % (tournament, table_number)
-            elif table_number < 100 and table_number > 9:
-                regex = r"Winamax\s+([^\(]+)\(%s\)\(#0%s\)" % (tournament, table_number)
-            else:
-                regex = r"Winamax\s+([^\(]+)\(%s\)\(#00%s\)" % (tournament, table_number)
+            regex = r"Winamax\s+([^\(]+)\(%s\)\(#0*%s\)" % (tournament, table_number)
 
             log.debug("regex get mtt sng expresso cash title:", regex)
         log.info(f"Winamax.getTableTitleRe: returns: '{regex}'")
```

**Comment by jejellyroll-fr** [comment]
I like the idea...it would allow the user to have a solution even when the regex doesn't match the table...on the realization, given the heterogeneity of the solutions used in particular by the different Linux distributions...it may be necessary to have an approach with a predefined table placement matrix... it's worth thinking about it.
