### ISSUE TITLE
[ISSUE] HUD crash - RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by brunetton** [jejellyroll-fr/fpdb-3#63]
**Describe the bug**

After changing table in tournamants, HUD crashes:

```
2024-11-19 22:19:58,573 - hud - DEBUG - Moved to a new table, killing current HUD
2024-11-19 22:19:58,573 - hud - DEBUG - kill_hud event
Traceback (most recent call last):
  File "/home/bruno/dev/forks/fpdb-3/HUD_main.pyw", line 188, in handle_message
    self.read_stdin(hand_id)
  File "/home/bruno/dev/forks/fpdb-3/HUD_main.pyw", line 352, in read_stdin
    for k in self.hud_dict:
RuntimeError: dictionary changed size during iteration

```
**To Reproduce**
1. Play a tournamanet
2. Wait to change table

**Desktop (please complete the following information):**
 - Version dev @314e79c22f9d26d93c65e59cd076eed9b1a54c5f

**Comment by jejellyroll-fr** [comment]
hello Bruno,

indeed, if we iterate directly on the dictionary and its size changes ... let's try with a copy:
replace line 352:
 for k in self.hud_dict: 

 by:
 
  for k in list(self.hud_dict.keys()):

**Comment by jejellyroll-fr** [comment]
hello @brunetton 

this issue is solved on my PR 64 ... just tested it under linux

i don't know if you have time to look at it ... if not i will merge my PR 64  it in dev at end of week-end ;)

**Comment by brunetton** [comment]
Testing right now ... :partying_face:

**Comment by brunetton** [comment]
I think we're good now :) Seems to work for me :+1:
