### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by sf-87** [jejellyroll-fr/fpdb-3#7]
I've tried the build script... Had to force OS = "Windows" cause $PSVersionTable.Platform is an empty string (?) and remove the pokereval file from add data since it's missing.
The build finally completed, but once again when launching fpdb.exe this occur:

![image](https://github.com/user-attachments/assets/d4c32c85-37b2-4e01-a711-a30c8abcfd79)

When launching HUD_main.exe from fpdb dist instead this occur:

![image](https://github.com/user-attachments/assets/7e28ee75-afc5-4d08-8cfc-dbae07df99c4)

Launching HUD_main.exe from its own dir works for like 3 seconds then seems to autoclose (or crash?)

**Comment by jejellyroll-fr** [comment]
i update the script windows for detection ... i doubt it will solve your problem
i added another script in bash, if you have git bash install you can try it also

 i will try to reproduce your config on a vm ...seems to a little different with win 10 +python 3.12

**Comment by jejellyroll-fr** [comment]
i succeed also to buildit in github ci and works on my windows ...can you try: https://github.com/jejellyroll-fr/fpdb-3/actions/runs/10023567608/artifacts/1722364393

**Comment by sf-87** [comment]
Nope, both the new ps1 and sh complete the build but then launching the exe provide the same errors...
I downloaded the artifact you generated and it works, but your fpdb.exe is 26MB, mine is 17MB so clearly something is missing. Plus I don't have an "_internal" folder
I suspect it has to do with my python environment... I try to create a new one under 3.11.9 and if still doesn't work I can only imagine to compare every package version and see what I have different from you :-(

**Comment by jejellyroll-fr** [comment]
really weird ... do you use pyenv ou conda?

**Comment by sf-87** [comment]
I use conda, and clearly has to do with the missing _internal folder because if I delete it from your build result the exe doesn't work either

**Comment by sf-87** [comment]
This are packages' versions:

![image](https://github.com/user-attachments/assets/35f4a55c-69fe-4298-a87f-5ce2b8957ff0)
![image](https://github.com/user-attachments/assets/94e02939-d5be-4671-bfb2-f4539bc6befe)
![image](https://github.com/user-attachments/assets/ab466ac1-16b8-4c2d-af90-4a3c0da40a24)
![image](https://github.com/user-attachments/assets/ce72fc97-d254-42f1-a773-429e57615a94)
![image](https://github.com/user-attachments/assets/5a5498ec-f904-4097-9dc5-28c1eada876b)
![image](https://github.com/user-attachments/assets/22d42c53-1322-4afc-a056-32b712772510)

see something different?

**Comment by jejellyroll-fr** [comment]
yes some minor
altgraph                  0.17.4    
certifi                   2024.6.2
email_validator           2.1.1
PyQt5                     5.15.6
PyQt5-sip                 12.13.0
pywin32                   306
pywin32-ctypes            0.2.2
uvicorn                   0.30.1

and this major, i hope it the problem:
pyinstaller               6.9.0
pyinstaller-hooks-contrib 2024.7

a little pip list (to see what libs you have install)

i will explore other tools to build for multiple os

**Comment by sf-87** [comment]
Not sure you saw my edit, but I realised the pyinstaller myself and once updated the build worked... Now I change the versions you wrote to have the same develop environment

**Comment by sf-87** [comment]
Ok, I see you updated the requirements.txt and I run it again, now we should have the exact same things:

Package                   Version
------------------------- ---------
altgraph                  0.17.4
annotated-types           0.7.0
anyio                     4.4.0
asttokens                 2.4.1
auto-py-to-exe            2.44.1
beautifulsoup4            4.12.3
blinker                   1.8.2
bottle                    0.12.25
bottle-websocket          0.2.9
bs4                       0.0.2
certifi                   2024.6.2
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
comm                      0.2.2
configparser              7.0.0
contourpy                 1.2.1
cycler                    0.12.1
debugpy                   1.8.2
decorator                 5.1.1
dnspython                 2.6.1
Eel                       0.17.0
email_validator           2.1.1
exceptiongroup            1.2.2
executing                 2.0.1
fastapi                   0.111.0
fastapi-cli               0.0.4
Flask                     3.0.3
fonttools                 4.53.0
future                    1.0.0
gevent                    24.2.1
gevent-websocket          0.10.1
greenlet                  3.0.3
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
idna                      3.7
importlib_metadata        8.0.0
ipykernel                 6.29.5
ipython                   8.26.0
itsdangerous              2.2.0
jedi                      0.19.1
Jinja2                    3.1.4
jupyter_client            8.6.2
jupyter_core              5.7.2
kiwisolver                1.4.5
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.0
matplotlib-inline         0.1.7
mdurl                     0.1.2
mplfinance                0.12.10b0
nest-asyncio              1.6.0
numpy                     1.26.4
orjson                    3.10.4
packaging                 24.1
pandas                    2.2.2
parso                     0.8.4
pefile                    2023.2.7
pickleshare               0.7.5
pillow                    10.3.0
pip                       24.1.2
platformdirs              4.2.2
pokereval                 0.2.0
prompt_toolkit            3.0.47
psutil                    6.0.0
pure-eval                 0.2.2
pycparser                 2.22
pydantic                  2.7.4
pydantic_core             2.18.4
Pygments                  2.18.0
pyinstaller               6.9.0
pyinstaller-hooks-contrib 2024.7
pyparsing                 3.1.2
PyQt5                     5.15.6
PyQt5-Qt5                 5.15.2
PyQt5-sip                 12.13.0
python-dateutil           2.9.0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
pywin32                   306
pywin32-ctypes            0.2.2
PyYAML                    6.0.1
pyzmq                     26.0.3
QDarkStyle                3.2.3
qt-material               2.14
QtPy                      2.4.1
requests                  2.32.3
rich                      13.7.1
setuptools                69.5.1
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
soupsieve                 2.5
SQLAlchemy                1.4.46
stack-data                0.6.2
starlette                 0.37.2
tornado                   6.4.1
traitlets                 5.14.3
typer                     0.12.3
typing_extensions         4.12.2
tzdata                    2024.1
ujson                     5.10.0
urllib3                   2.2.2
uvicorn                   0.30.1
watchfiles                0.22.0
wcwidth                   0.2.13
websockets                12.0
Werkzeug                  3.0.3
wheel                     0.43.0
whichcraft                0.6.1
xcffib                    1.5.0
xlrd                      2.0.1
zipp                      3.19.2
zope.event                5.0
zope.interface            6.4.post2
